export const GET_SHOPPING_ITEMS = "GET_SHOPPING_ITEMS";
export const ADD_SHOPPING_ITEMS = "ADD_SHOPPING_ITEMS";
export const DELETE_SHOPPING_ITEMS = "DELETE_SHOPPING_ITEMS";

export const GET_RECIPES = "GET_RECIPES";
